name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_ubuntu:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["12.10", "12.16", "12.x", "14.x", "16.x", "17.x"]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm test

  build_windows:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: ["12.10", "12.16", "12.x", "14.x", "16.x", "17.x"]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm test
