name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_ubuntu:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["14.x", "16.x", "18.x", "20.x"]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm test

  build_windows:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: ["14.x", "16.x", "18.x", "20.x"]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - if: matrix.node-version == '14.x'
      run: npm install -g npm@9 # node 14 comes with npm 6, which has some known bugs with dependency resolution
    - run: npm i
    - run: npm test
